name: CI

on:
  push:
    branches:
      - "v1.8.6-with-ruby3-compat"
  pull_request:
    branches:
      - "v1.8.6-with-ruby3-compat"

jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        ruby-version: ['2.7', '3.0']

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - name: Run tests
        run: |
          bundle exec rake test
